import Footer from "./components/Footer"
import Header from "./components/Header"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{
        width: '100vw',
        height: "100vh",
        display: 'flex',
        padding: 0,
        margin: 0,
        textAlign: "center",
        flexDirection: "column",
        justifyContent: "space-between",

      }}>
        <Header/>
          {children}
        <Footer/>
      </body>
    </html>
  )
}
